### ISSUE TITLE
ResultSet releases Connection only on destruction, taking all capacity from Pool

### ISSUE THREAD

**Issue by psafarov** [amphp/sql-common#2]
In the following code only `gc_collect_cycles()` prevents the `Pool` to run out of connections, otherwise connections don't get released on time. I believe `Connection` has to be released when the `ResultSet` reaches its end, not only on `ResultSet` destruction.

```php
while (true) {
    $resultSet = yield $pool->query("SELECT 1");
    yield \Amp\Iterator\toArray($resultSet);

    gc_collect_cycles();

    yield new Delayed(5000);
}
```

**Comment by xpader** [comment]
You can call $result->advance() or $result->nextResultSet() again after query to release connection, because result can not confirm the connection can be idle..
